source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.1.0"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.16.2', '< 2.0'
gem 'activesupport', '>= 7.2.3.1', '< 8.0'
gem 'xcodeproj', '>= 1.27.0', '< 2.0'

# Newer Ruby releases have removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
gem 'tsort'
