name: Notice yarn.lock changes
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Notice yarn.lock changes
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          collapsibleThreshold: '25'
          failOnDowngrade: 'false'
          path: 'yarn.lock'
          updateComment: 'true'
